/* Full real workflow with synthetic providers; not clinical or ASR accuracy evaluation. */
const fs=require('node:fs/promises');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');
let server,browser;
const deadline=setTimeout(()=>{console.error('Browser validation timed out');process.exit(1);},120000);
(async()=>{
 const assert=require('node:assert/strict');
 const path=require('node:path');
 server=require('node:child_process').spawn('python',['tests/evidence_fixture.py'],{cwd:path.resolve(__dirname,'..'),stdio:['ignore','ignore','pipe']});server.stderr.on('data',d=>process.stderr.write(d));process.on('exit',()=>server.kill());
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:8765/api/desk/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const shots=process.env.QA_SHOTS_DIR || '/tmp/medflow-evidence-qa';await fs.mkdir(shots,{recursive:true});
 browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM_PATH || undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-software-rasterizer'],headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:900}});
 const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.goto('http://127.0.0.1:8765/consultation/login');await p.waitForTimeout(300);await p.screenshot({path:shots+'/login.png',fullPage:true});
 await p.locator('#loginEmail').fill('audit@example.test');await p.locator('#loginPassword').fill('AuditPass123!');await p.locator('#loginSubmit').click();
 await p.waitForURL('**/workspace');await p.waitForFunction(()=>allPatients.length===2 && ws?.readyState===WebSocket.OPEN);
 await p.waitForTimeout(300);await p.screenshot({path:shots+'/today.png',fullPage:true});
 await p.locator('#dashboardPatientList .patient-row').first().click();await p.waitForFunction(()=>!visitLoading);
 console.log('READ ONLY OPEN',await p.evaluate(()=>({workflow:activeWorkflow,encounter:activeEncounter,stage:visitStage})));
 await p.waitForTimeout(300);await p.screenshot({path:shots+'/prepare.png',fullPage:true});
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>activeWorkflow?.state==='PATIENT_UNVERIFIED');
 await p.locator('#visitNextBtn').click();await p.getByRole('button',{name:'Use phone OTP instead',exact:true}).click();await p.locator('#verificationDialog').waitFor({state:'visible'});await p.locator('#patientOtpInput').fill('123456');await p.locator('#verificationDialog').getByRole('button',{name:'Verify patient',exact:true}).click();await p.waitForFunction(()=>activeWorkflow?.state==='BOOKING_REQUIRED');
 await p.locator('#visitNextBtn').click();await p.locator('#bookingDialog').waitFor({state:'visible'});
 console.log('BOOKING FIELDS',await p.locator('#bookingDoctor').innerText());
 await p.getByRole('button',{name:'Find slots',exact:true}).click();await p.waitForFunction(()=>document.getElementById('bookingSlot').options.length>1);
 await p.locator('#bookingSlot').selectOption({index:1});await p.getByRole('button',{name:'Confirm appointment',exact:true}).click();await p.waitForFunction(()=>activeWorkflow?.state==='BOOKING_CONFIRMED');
 await p.locator('#visitNextBtn').click();await p.locator('#consentDialog').waitFor({state:'visible'});for(const id of ['consentRecording','consentTranscription','consentDocumentation'])await p.locator('#'+id).check();await p.getByRole('button',{name:'Save choices',exact:true}).click();await p.waitForFunction(()=>hasRequiredConsent());
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>visitStage==='capture');await p.waitForTimeout(300);await p.screenshot({path:shots+'/capture.png',fullPage:true});


 const checkLayout=async(label)=>{for(const width of [1440,1280,390]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:shots+'/'+label+'-'+width+'.png',fullPage:true});}await p.setViewportSize({width:1440,height:900});};
 assert.equal(await p.locator('#automaticSoapToggle').isChecked(),false);
 assert.equal(await p.locator('.transcript-card').isVisible(),false);
 assert.equal(await p.locator('.soap-card').isVisible(),false);
 await checkLayout('capture');
 // Exercise the actual microphone start handler using synthetic browser audio.
 await p.evaluate(()=>{window.qaAudio=new AudioContext();const oscillator=qaAudio.createOscillator(),gain=qaAudio.createGain(),destination=qaAudio.createMediaStreamDestination();oscillator.frequency.value=440;gain.gain.value=0.2;oscillator.connect(gain).connect(destination);oscillator.start();navigator.mediaDevices.getUserMedia=async()=>destination.stream;});
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>isRecording);
 const identity=await p.evaluate(()=>({workflow:activeWorkflow.workflow_id,encounter:activeEncounter.encounter_id,patient:selectedPatient._id}));
 await p.waitForTimeout(1800);await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>isProcessing);
 await p.reload();await p.waitForFunction(()=>!visitLoading && isProcessing);
 await p.waitForFunction(()=>visitStage==='transcript' && !visitLoading && !isProcessing);
 assert.equal(await p.evaluate(()=>Boolean(soapLastSavedNoteId)),false);
 assert.equal((await (await fetch('http://127.0.0.1:8765/audit/soap-controls')).json()).soap_calls,0);
 assert.equal(await p.locator('.transcript-card').isVisible(),true);assert.equal(await p.locator('.soap-card').isVisible(),false);
 await p.locator('#guidedProcessToggle').click();assert.equal(await p.locator('.process-inspection').isVisible(),true);
 await p.evaluate(()=>toggleProcessInspection());assert.equal(await p.locator('#processObservatory').isVisible(),false);
 await checkLayout('transcript');
 await p.locator('[data-edit-conversation]').first().click();await p.locator('[data-turn-english]').fill('Temporary edit');await p.locator('[data-turn-cancel]').click();
 assert.equal(await p.evaluate(()=>conversationDirty),false);
 await p.locator('[data-edit-conversation]').first().click();await p.locator('[data-turn-english]').fill('Clinician corrected synthetic wording.');await p.locator('[data-turn-role]').selectOption('DOCTOR');await p.locator('[data-turn-done]').click();
 const patient=await p.evaluate(()=>selectedPatient._id);await p.evaluate(()=>openPatientVisit(allPatients[1]));assert.equal(await p.evaluate(()=>selectedPatient._id),patient);
 assert.equal(await p.locator('#visitNextBtn').innerText().then(x=>x.trim()),'Save conversation changes');
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>!visitActionBusy && conversationReview?.revision===2 && !conversationDirty);
 assert.equal(await p.evaluate(()=>Boolean(soapLastSavedNoteId)),false);assert.equal(await p.evaluate(()=>fullTranscript[0].clinical_english),'Clinician corrected synthetic wording.');
 await p.reload();await p.waitForFunction(()=>!visitLoading && conversationReview?.revision===2 && visitStage==='transcript');
 assert.equal(await p.evaluate(()=>fullTranscript[0].clinical_english),'Clinician corrected synthetic wording.');
 await p.evaluate(()=>fetch('/audit/soap-controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fail_soap:true})}));
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>!visitActionBusy && conversationReview?.status==='SOAP_FAILED' && visitStage==='transcript');
 assert.equal(await p.evaluate(()=>activeEncounter.encounter_id),identity.encounter);
 assert.equal(await p.locator('#visitNextBtn').innerText().then(x=>x.trim()),'Retry SOAP generation');
 await p.evaluate(()=>fetch('/audit/soap-controls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({soap_delay:4})}));
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>isProcessing);await p.reload();await p.waitForFunction(()=>!visitLoading && isProcessing);
 await p.waitForFunction(()=>soapLastSavedNoteId && visitStage==='review' && !isProcessing);
 assert.equal(await p.evaluate(()=>activeEncounter.encounter_id),identity.encounter);
 assert.equal(await p.locator('.transcript-card').isVisible(),false);assert.equal(await p.locator('.soap-card').isVisible(),true);
 await checkLayout('soap');await p.locator('#conversationSourceToggle').click();assert.equal(await p.locator('.transcript-card').isVisible(),true);await p.locator('#conversationSourceToggle').click();assert.equal(await p.locator('.transcript-card').isVisible(),false);
 await p.locator('.evidence-soap-text .evidence-span').first().click();await p.locator('#evidenceDialog [data-evidence-source]').first().click();assert.equal(await p.locator('.transcript-card').isVisible(),true);
 await p.locator('#conversationSourceToggle').click();
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>generatedNoteState==='REVIEW_REQUIRED' && !visitActionBusy);await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>generatedNoteState==='APPROVED_BY_DOCTOR' && visitStage==='finish' && !visitActionBusy);
 await p.locator('#visitSummaryLanguage').selectOption('ENGLISH');await p.getByRole('button',{name:'Generate summary',exact:true}).click();await p.waitForFunction(()=>!summaryBusy && !!afterVisitSummaries[soapLastSavedNoteId]);
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>activeWorkflow?.state==='ENCOUNTER_COMPLETED');
 assert.equal(await p.evaluate(()=>activeAppointment.status),'COMPLETED');assert.equal(await p.evaluate(()=>activeWorkflow.workflow_id),identity.workflow);
 console.log('GUIDED: capture → refresh → transcript → saved correction → failed SOAP → retry/refresh → sources → approval → summary → completion passed');
 // Existing automatic path remains available, persisted locally, and uses the same backend.
 await p.evaluate(()=>openPatientVisit(allPatients[1]));await p.waitForFunction(()=>!visitLoading);
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>activeWorkflow?.state==='PATIENT_UNVERIFIED');
 await p.locator('#visitNextBtn').click();await p.getByRole('button',{name:'Use phone OTP instead',exact:true}).click();await p.locator('#patientOtpInput').fill('123456');await p.locator('#verificationDialog').getByRole('button',{name:'Verify patient',exact:true}).click();await p.waitForFunction(()=>activeWorkflow?.state==='BOOKING_REQUIRED');
 await p.locator('#visitNextBtn').click();await p.getByRole('button',{name:'Find slots',exact:true}).click();await p.waitForFunction(()=>document.getElementById('bookingSlot').options.length>1);await p.locator('#bookingSlot').selectOption({index:1});await p.getByRole('button',{name:'Confirm appointment',exact:true}).click();await p.waitForFunction(()=>activeWorkflow?.state==='BOOKING_CONFIRMED');
 await p.locator('#visitNextBtn').click();for(const id of ['consentRecording','consentTranscription','consentDocumentation'])await p.locator('#'+id).check();await p.getByRole('button',{name:'Save choices',exact:true}).click();await p.waitForFunction(()=>hasRequiredConsent());await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>visitStage==='capture');
 await p.locator('#automaticSoapToggle').check();await p.locator('#automaticSoapToggle').uncheck();assert.equal(await p.evaluate(()=>window.medflowAutomaticSoap),false);
 await p.locator('#automaticSoapToggle').check();assert.equal(await p.evaluate(()=>window.medflowAutomaticSoap),true);assert.equal(await p.evaluate(()=>localStorage.getItem('medflow-automatic-soap')),'true');
 await p.evaluate(()=>{window.qaAudio=new AudioContext();const oscillator=qaAudio.createOscillator(),destination=qaAudio.createMediaStreamDestination();oscillator.connect(destination);oscillator.start();navigator.mediaDevices.getUserMedia=async()=>destination.stream;});
 await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>isRecording);await p.waitForTimeout(1800);await p.locator('#visitNextBtn').click();await p.waitForFunction(()=>soapLastSavedNoteId && visitStage==='review' && !isProcessing);
 await p.evaluate(()=>refreshActiveContext());assert.equal(await p.evaluate(()=>conversationReview.auto_soap),true);
 assert.equal(await p.locator('.transcript-card').isVisible(),false);assert.deepEqual(errors,[]);
 console.log('AUTOMATIC toggle + actual microphone handler passed; three viewport layouts passed; page errors: 0');
 await browser.close();server.kill();clearTimeout(deadline);
})().catch(async e=>{console.error(e);clearTimeout(deadline);await browser?.close();server?.kill();process.exitCode=1});
