from __future__ import annotations

from enum import Enum


class UserRole(str, Enum):
    RECEPTIONIST = "RECEPTIONIST"
    DOCTOR = "DOCTOR"
    ADMINISTRATOR = "ADMINISTRATOR"
    SYSTEM = "SYSTEM"


class AppointmentStatus(str, Enum):
    REQUESTED = "REQUESTED"
    CONFIRMED = "CONFIRMED"
    CHECKED_IN = "CHECKED_IN"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class EncounterStatus(str, Enum):
    PLANNED = "PLANNED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    DOCUMENTATION = "DOCUMENTATION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class WorkflowState(str, Enum):
    PATIENT_UNVERIFIED = "PATIENT_UNVERIFIED"
    PATIENT_VERIFIED = "PATIENT_VERIFIED"
    INTAKE_IN_PROGRESS = "INTAKE_IN_PROGRESS"
    INTAKE_COMPLETED = "INTAKE_COMPLETED"
    BOOKING_REQUIRED = "BOOKING_REQUIRED"
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    PATIENT_CHECKED_IN = "PATIENT_CHECKED_IN"
    CONSULTATION_READY = "CONSULTATION_READY"
    CONSULTATION_ACTIVE = "CONSULTATION_ACTIVE"
    DOCUMENTATION_PROCESSING = "DOCUMENTATION_PROCESSING"
    NOTE_REVIEW_REQUIRED = "NOTE_REVIEW_REQUIRED"
    NOTE_APPROVED = "NOTE_APPROVED"
    ENCOUNTER_COMPLETED = "ENCOUNTER_COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    HUMAN_ASSISTANCE_REQUIRED = "HUMAN_ASSISTANCE_REQUIRED"


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    LOCKED = "LOCKED"
    EXPIRED = "EXPIRED"


class ConsentType(str, Enum):
    AUDIO_RECORDING = "AUDIO_RECORDING"
    AI_TRANSCRIPTION = "AI_TRANSCRIPTION"
    AI_DOCUMENTATION = "AI_DOCUMENTATION"
    AUDIO_RETENTION = "AUDIO_RETENTION"


class Speaker(str, Enum):
    DOCTOR = "DOCTOR"
    PATIENT = "PATIENT"
    NURSE = "NURSE"
    # Parent, guardian, spouse, or relative speaking on the patient's behalf.
    ATTENDANT = "ATTENDANT"
    UNKNOWN = "UNKNOWN"


class ClaimSupportStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class NoteStatus(str, Enum):
    AI_DRAFT = "AI_DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED_BY_DOCTOR = "APPROVED_BY_DOCTOR"
    REJECTED = "REJECTED"
    AMENDED = "AMENDED"


class CodeSuggestionStatus(str, Enum):
    SUGGESTED = "SUGGESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class SummaryLanguage(str, Enum):
    ENGLISH = "ENGLISH"
    URDU = "URDU"
    BILINGUAL = "BILINGUAL"
