from __future__ import annotations

from typing import Protocol

from medflow.domain.enums import ConsentType, SummaryLanguage
from medflow.domain.models import (
    AfterVisitSummary,
    Appointment,
    AuditEvent,
    ClinicalTemplate,
    CodeSuggestion,
    ConsentRecord,
    Encounter,
    Patient,
    PreVisitSummary,
    SOAPNote,
    SOAPNoteVersion,
    TranscriptRecord,
    VerificationRecord,
    WorkflowSession,
)


class PatientRepository(Protocol):
    def get(self, patient_id_or_legacy_ref: str) -> Patient | None: ...
    def list(self) -> list[Patient]: ...
    def save(self, patient: Patient) -> Patient: ...


class AppointmentRepository(Protocol):
    def get(self, appointment_id: str) -> Appointment | None: ...
    def list(self, *, patient_id: str | None = None, practitioner_id: str | None = None) -> list[Appointment]: ...
    def get_by_idempotency_key(self, idempotency_key: str) -> Appointment | None: ...
    def save(self, appointment: Appointment) -> Appointment: ...


class EncounterRepository(Protocol):
    def get(self, encounter_id: str) -> Encounter | None: ...
    def list(self, *, patient_id: str | None = None) -> list[Encounter]: ...
    def save(self, encounter: Encounter) -> Encounter: ...


class WorkflowRepository(Protocol):
    def get(self, workflow_id: str) -> WorkflowSession | None: ...
    def list(self, *, patient_id: str | None = None) -> list[WorkflowSession]: ...
    def save(self, workflow: WorkflowSession, *, expected_version: int | None = None) -> WorkflowSession: ...


class VerificationRepository(Protocol):
    def get(self, challenge_id: str) -> VerificationRecord | None: ...
    def latest_for_patient(self, patient_id: str) -> VerificationRecord | None: ...
    def save(self, verification: VerificationRecord) -> VerificationRecord: ...


class ConsentRepository(Protocol):
    def get(self, consent_id: str) -> ConsentRecord | None: ...
    def list_for_encounter(self, encounter_id: str) -> list[ConsentRecord]: ...
    def latest(self, encounter_id: str, consent_type: ConsentType) -> ConsentRecord | None: ...
    def save(self, consent: ConsentRecord) -> ConsentRecord: ...


class NoteRepository(Protocol):
    def get(self, note_id: str) -> SOAPNote | None: ...
    def list(self, *, patient_id: str | None = None, encounter_id: str | None = None) -> list[SOAPNote]: ...
    def save(self, note: SOAPNote) -> SOAPNote: ...
    def get_version(self, note_version_id: str) -> SOAPNoteVersion | None: ...
    def list_versions(self, note_id: str) -> list[SOAPNoteVersion]: ...
    def save_version(self, version: SOAPNoteVersion) -> SOAPNoteVersion: ...


class TranscriptRepository(Protocol):
    def get(self, transcript_id: str) -> TranscriptRecord | None: ...
    def save(self, transcript: TranscriptRecord) -> TranscriptRecord: ...


class PreVisitSummaryRepository(Protocol):
    def latest(self, patient_id: str) -> PreVisitSummary | None: ...
    def save(self, summary: PreVisitSummary) -> PreVisitSummary: ...


class AfterVisitSummaryRepository(Protocol):
    def get_for_encounter(
        self,
        encounter_id: str,
        *,
        language: SummaryLanguage | None = None,
    ) -> AfterVisitSummary | None: ...
    def save(self, summary: AfterVisitSummary) -> AfterVisitSummary: ...


class TemplateRepository(Protocol):
    def get(self, template_id: str) -> ClinicalTemplate | None: ...
    def list(self, *, active_only: bool = True) -> list[ClinicalTemplate]: ...
    def save(self, template: ClinicalTemplate) -> ClinicalTemplate: ...


class CodeSuggestionRepository(Protocol):
    def get(self, suggestion_id: str) -> CodeSuggestion | None: ...
    def list_for_note(self, note_id: str) -> list[CodeSuggestion]: ...
    def save(self, suggestion: CodeSuggestion) -> CodeSuggestion: ...
    def delete(self, suggestion_id: str) -> None: ...


class AuditRepository(Protocol):
    def append(self, event: AuditEvent) -> AuditEvent: ...
    def list(self, *, patient_ref: str | None = None, event_type: str | None = None) -> list[AuditEvent]: ...
